name: 'Firebase Emulator Action'
description: 'Starts the Firebase Emulator Suite'
author: 'Invertase'

inputs:
  firebase-tools-version:
    description: 'Firebase Tools version to install'
    required: false
    default: 'latest'
  emulators:
    description: 'Comma-separated list of Firebase emulators to start (e.g., auth,firestore,functions)'
    required: false
    default: 'auth,firestore,functions,storage,database'
  project-id:
    description: 'The project ID to use for the Firebase Emulator Suite'
    required: false
    default: 'test-project'
  max-retries:
    description: 'The maximum number of retries to attempt when starting the Firebase Emulator Suite'
    required: false
    default: '3'
  max-checks:
    description: 'The maximum number of checks to attempt when starting the Firebase Emulator Suite'
    required: false
    default: '60'
  wait-time:
    description: 'The time to wait (in seconds) between checks when starting the Firebase Emulator Suite'
    required: false
    default: '1'
  check-port:
    description: 'The port to check for when starting the Firebase Emulator Suite'
    required: false
    default: '8080' # Firestore emulator default port

runs:
  using: "composite"
  steps:
    - name: Install Firebase Tools
      shell: bash
      run: |
       sudo npm i -g firebase-tools@${{ inputs.firebase-tools-version }}

    - name: Check and strip spaces from emulators input (if necessary)
      shell: bash
      run: |
        EMULATORS="${{ inputs.emulators }}"
        
        # Check if there are spaces around the commas
        if [[ "$EMULATORS" =~ [[:space:]] ]]; then
          echo "Spaces detected in emulators list, stripping spaces..."
          # Remove spaces around commas
          EMULATORS=$(echo "$EMULATORS" | tr -s ' ' ',')
          EMULATORS=$(echo "$EMULATORS" | tr -s ',' ',')  # Ensure no accidental extra commas
        else
          echo "No spaces detected in emulators list."
        fi
        
        # Output the result for debugging purposes
        echo "Stripped emulators list: $EMULATORS"
        echo "EMULATORS=$EMULATORS" >> $GITHUB_ENV

    - name: Start Firebase Emulator
      shell: bash
      run: |
       chmod +x ./start-firebase-emulator.sh && ./start-firebase-emulator.sh ${{ inputs.emulators }} ${{ inputs.project-id }} ${{ inputs.max-retries }} ${{ inputs.max-checks }} ${{ inputs.wait-time }} ${{ inputs.check-port }}