name: Test Firebase Emulator Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (since your action requires it)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Set up Java (since your action requires it)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Run your Firebase Emulator Action
      - name: Run Firebase Emulator Action
        uses: ./ # Uses the current repository as an action
        with:
          node-version: '20'
          java-version: '17'
          firebase-tools-version: 'latest'
          emulators: 'auth'
          project-id: 'test-project'
          max-retries: '3'
          max-checks: '60'
          wait-time: '1'
          check-port: '9099'